### ISSUE TITLE
package.json not installed but package-lock.json installed

### ISSUE THREAD

**Issue by pujakumari09** [package-community/discussions#7]
i have installed morgan, body-parser and express but package.json file has not come up but package-lock.json has been installed and i don't understand how package-lock.json is there without package.json

**Comment by larsgw** [comment]
You'd have to create a `package.json` yourself first (`npm init`) before installing. If you have no `package.json`, npm walks up the file tree until it finds a `package.json` and/or `node_modules/`, where it then installs dependencies. The dependencies may have been installed in your home directory. [docs](https://docs.npmjs.com/files/folders#more-information)

Note: you're more likely to receive npm support on https://npm.communtiy

**Comment by pujakumari09** [comment]
> You'd have to create a `package.json` yourself first (`npm init`) before installing. If you have no `package.json`, npm walks up the file tree until it finds a `package.json` and/or `node_modules/`, where it then installs dependencies. The dependencies may have been installed in your home directory. [docs](https://docs.npmjs.com/files/folders#more-information)
> 
> Note: you're more likely to receive npm support on https://npm.communtiy

Thanks for the help.
